# Generated by Django 3.1.6 on 2021-03-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210318_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Name', max_length=20)),
                ('password', models.CharField(default='Password', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='Password', max_length=10),
        ),
    ]
