# Generated by Django 3.1.6 on 2021-03-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210319_0701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
